import "~/styles/globals.css";

import { Inter } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { getServerAuthSession } from "~/server/auth";
import AuthProvider from "./context/client-auth-provider";
import { LoginModal } from "./_components/modal/modals";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "TAILS",
  description:
    "Generated by create-t3-appThe Animal Institution for Lifesaving and Sanctuary ",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerAuthSession();

  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <TRPCReactProvider>
          <AuthProvider session={session}>
            <LoginModal />
            <div className="mx-auto w-full max-w-lg pt-24 xl:max-w-xl">
              {children}
            </div>
          </AuthProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
